---
bibliography: references.bib
output: github_document
---

# Text Mining for Urban Farming: gaining new insights by synthesising archaeological and archaeobotanical research with the help of computational methods and conventional analyses

This reposistory contains the presentation given during the IWGP 2025 in Groningen (<https://archaeobotany.org/iwgp2025/>) on Monday July 21, 2025. This presentation was presented in the session "Session 9: The Archaeobotany of Settlements and Urban Landscapes".

# Abstract (as submitted for the conference)

Urban farming is about food production for and by town dwellers and is partly known from documentary evidence. While research on urban farming in the Netherlands exists, the topic has nevertheless remained relatively underexposed in terms of historical, archaeological and archaeobotanical research. In a recently published volume, evidence for urban farming in Dutch towns between 1250 up to 1850 has been presented [@fischer2021]. In this synthesizing research we applied an innovative method that combines text mining with conventional reading and analysing (grey) literature from commercially funded urban excavations in the Netherlands carried out between 1997 and 2017. A list of relevant (archaeobotanical) keywords was used to mine the text of 1380 published reports. This technique was used to filter relevant reports for further in-depth analyses, generating diachronic data on historic farming in 84 towns. The method that we applied is innovative, transparent and open. We have made all code of the analyses available [@visser], because we value Open Science and reproducibility. In the research quantitative and qualitative approaches were combined to understand the nature of urban farming in the Netherlands, resulting in the discovery of small details and large patterns during this long and dynamic time period. In this interdisciplinary paper we will explore three main themes: methodology, results and future applications for and beyond archaeobotany.

# References
